### ISSUE TITLE
lazagne and ttyrec module error on CentOS 6 victim

### ISSUE THREAD

**Issue by j3ssie** [n1nj4sec/pupy#676]
After I got session on my CentOS 6 victim by using python payload and run lazagne and ttyrec module I got these Error below.
```
========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "rpyc/core/protocol.py", line 347, in _dispatch_request
  File "rpyc/core/protocol.py", line 630, in _handle_getattr
  File "rpyc/core/protocol.py", line 596, in _access_attr
AttributeError: 'module' object has no attribute 'run_lazagne'
Traceback (most recent call last):
  File "/root/pentest/pupy/pupy/pupylib/PupyJob.py", line 161, in module_worker
    module.run(self.args)
  File "/root/pentest/pupy/pupy/modules/lazagne.py", line 67, in run
    runLaZagne = self.client.remote('lazagne.config.run', 'run_lazagne', False)
  File "/root/pentest/pupy/pupy/pupylib/PupyClient.py", line 234, in remote
    remote_function = getattr(self.conn.modules[module], function)
  File "/root/pentest/pupy/pupyw/local/lib/python2.7/site-packages/rpyc/core/netref.py", line 153, in __getattr__
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/root/pentest/pupy/pupyw/local/lib/python2.7/site-packages/rpyc/core/netref.py", line 72, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/root/pentest/pupy/pupy/network/lib/connection.py", line 381, in sync_request
    raise obj
AttributeError: 'module' object has no attribute 'run_lazagne'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "rpyc/core/protocol.py", line 347, in _dispatch_request
  File "rpyc/core/protocol.py", line 630, in _handle_getattr
  File "rpyc/core/protocol.py", line 596, in _access_attr
AttributeError: 'module' object has no attribute 'run_lazagne'

[-] 'module' object has no attribute 'run_lazagne'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "rpyc/core/protocol.py", line 347, in _dispatch_request
  File "rpyc/core/protocol.py", line 630, in _handle_getattr
  File "rpyc/core/protocol.py", line 596, in _access_attr
AttributeError: 'module' object has no attribute 'run_lazagne'

```
and this is ffrom ttyrec
```
>>  run ttyrec start
[!] [M/C:TTYRec] Exception: Traceback (most recent call last):
  File "", line 394, in create
  File "ttyrec.py", line 231, in __init__
  File "ttyrec.py", line 45, in __init__
  File "ttyrec.py", line 78, in validate
KProbesNotAvailable: Tracing using KProbes are not accessible/available
```

Whether these modules not work on CentOS or I did something wrong because I tested it on Ubuntu and Windows and it worked fine?

**Comment by alxchk** [comment]
ttyrec will work only on Linux and on very recent kernels. 
This thing uses kprobes kernel API which is very new thing.
It /may/ work with >=3.16, it works (but in some cases may crash kernel x_x) with >= 4.9, and looks stable with >= 4.14.

**Comment by alxchk** [comment]
According to your message LaZagne loaded to client is older than interface in modules. Likely you have been updated very short time ago. You probably should unload old module first with:
```
load_package -r lazagne 
load_package -r LaZagne
```

**Comment by j3ssie** [comment]
> ttyrec will work only on Linux and on very recent kernels.
> This thing uses kprobes kernel API which is very new thing.
> It /may/ work with >=3.16, it works (but in some cases may crash kernel x_x) with >= 4.9, and looks stable with >= 4.14.

I think my kernel version is fine for ttyrec, right?
```
Linux Myhostname 2.6.32-431.23.3.el6.x86_64 #1 SMP Thu Jul 31 17:20:51 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```



> According to your message LaZagne loaded to client is older than interface in modules. Likely you have been updated very short time ago. You probably should unload old module first with:
> 
> ```
> load_package -r lazagne 
> load_package -r LaZagne
> ```
After I successful run command above I still get same error and yeah I just preinstall pupy from Quick install and configure from README.md

**Comment by alxchk** [comment]
> 2.6.32

No. It's veeeeeery old. 2 < 4 :)

> After I successful run command above I still get same error and yeah I just preinstall pupy from Quick install and configure from README.md

Then LaZagne may be not loaded properly. When I have time I'll take a look on how it works with CentOS 6. Meanwhile you can show the output of

```
pyexec -c 'import lazagne.config.run; print dir(lazagne.config.run)'
```
